// Code generated by MockGen. DO NOT EDIT.
// Source: agent_commander.go
//
// Generated by this command:
//
//	mockgen -source=agent_commander.go -destination=mock/mock_agent_commander.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kakkky/hakoniwa/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentCommander is a mock of AgentCommander interface.
type MockAgentCommander struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCommanderMockRecorder
	isgomock struct{}
}

// MockAgentCommanderMockRecorder is the mock recorder for MockAgentCommander.
type MockAgentCommanderMockRecorder struct {
	mock *MockAgentCommander
}

// NewMockAgentCommander creates a new mock instance.
func NewMockAgentCommander(ctrl *gomock.Controller) *MockAgentCommander {
	mock := &MockAgentCommander{ctrl: ctrl}
	mock.recorder = &MockAgentCommanderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCommander) EXPECT() *MockAgentCommanderMockRecorder {
	return m.recorder
}

// PublishCommand mocks base method.
func (m *MockAgentCommander) PublishCommand(ctx context.Context, cmd domain.AgentCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCommand", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishCommand indicates an expected call of PublishCommand.
func (mr *MockAgentCommanderMockRecorder) PublishCommand(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCommand", reflect.TypeOf((*MockAgentCommander)(nil).PublishCommand), ctx, cmd)
}

// MockAgentCommand is a mock of AgentCommand interface.
type MockAgentCommand struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCommandMockRecorder
	isgomock struct{}
}

// MockAgentCommandMockRecorder is the mock recorder for MockAgentCommand.
type MockAgentCommandMockRecorder struct {
	mock *MockAgentCommand
}

// NewMockAgentCommand creates a new mock instance.
func NewMockAgentCommand(ctrl *gomock.Controller) *MockAgentCommand {
	mock := &MockAgentCommand{ctrl: ctrl}
	mock.recorder = &MockAgentCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCommand) EXPECT() *MockAgentCommandMockRecorder {
	return m.recorder
}

// _isAgentCommand mocks base method.
func (m *MockAgentCommand) _isAgentCommand() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "_isAgentCommand")
}

// _isAgentCommand indicates an expected call of _isAgentCommand.
func (mr *MockAgentCommandMockRecorder) _isAgentCommand() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "_isAgentCommand", reflect.TypeOf((*MockAgentCommand)(nil)._isAgentCommand))
}
