// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/mock_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	domain "github.com/kakkky/hakoniwa/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockResidentRepository is a mock of ResidentRepository interface.
type MockResidentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockResidentRepositoryMockRecorder
	isgomock struct{}
}

// MockResidentRepositoryMockRecorder is the mock recorder for MockResidentRepository.
type MockResidentRepositoryMockRecorder struct {
	mock *MockResidentRepository
}

// NewMockResidentRepository creates a new mock instance.
func NewMockResidentRepository(ctrl *gomock.Controller) *MockResidentRepository {
	mock := &MockResidentRepository{ctrl: ctrl}
	mock.recorder = &MockResidentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResidentRepository) EXPECT() *MockResidentRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockResidentRepository) GetAll() ([]*domain.Resident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*domain.Resident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockResidentRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockResidentRepository)(nil).GetAll))
}

// Save mocks base method.
func (m *MockResidentRepository) Save(resident *domain.Resident) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", resident)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockResidentRepositoryMockRecorder) Save(resident any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockResidentRepository)(nil).Save), resident)
}

// SaveAll mocks base method.
func (m *MockResidentRepository) SaveAll(residents []*domain.Resident) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAll", residents)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAll indicates an expected call of SaveAll.
func (mr *MockResidentRepositoryMockRecorder) SaveAll(residents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAll", reflect.TypeOf((*MockResidentRepository)(nil).SaveAll), residents)
}

// MockBuildingManagerRepository is a mock of BuildingManagerRepository interface.
type MockBuildingManagerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBuildingManagerRepositoryMockRecorder
	isgomock struct{}
}

// MockBuildingManagerRepositoryMockRecorder is the mock recorder for MockBuildingManagerRepository.
type MockBuildingManagerRepositoryMockRecorder struct {
	mock *MockBuildingManagerRepository
}

// NewMockBuildingManagerRepository creates a new mock instance.
func NewMockBuildingManagerRepository(ctrl *gomock.Controller) *MockBuildingManagerRepository {
	mock := &MockBuildingManagerRepository{ctrl: ctrl}
	mock.recorder = &MockBuildingManagerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildingManagerRepository) EXPECT() *MockBuildingManagerRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockBuildingManagerRepository) Get() (domain.BuildingManager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(domain.BuildingManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBuildingManagerRepositoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBuildingManagerRepository)(nil).Get))
}

// Save mocks base method.
func (m *MockBuildingManagerRepository) Save(BuildingManager *domain.BuildingManager) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", BuildingManager)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockBuildingManagerRepositoryMockRecorder) Save(BuildingManager any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBuildingManagerRepository)(nil).Save), BuildingManager)
}
