// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kakkky/hakoniwa/agents"
	"github.com/kakkky/hakoniwa/config"
	"github.com/kakkky/hakoniwa/infrastructure/agent"
	"github.com/kakkky/hakoniwa/infrastructure/file"
	"github.com/kakkky/hakoniwa/infrastructure/llm"
	"github.com/kakkky/hakoniwa/presentation/tui"
	"github.com/kakkky/hakoniwa/usecase"
)

// Injectors from wire.go:

func initializeApp() (*App, error) {
	llmProvider := llm.NewLLMGeminiProvider()
	agentCommandCh := agent.NewAgentCommandCh()
	runtime := agents.NewRuntime(llmProvider, agentCommandCh)
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	filePaths, err := file.NewFilePaths(configConfig)
	if err != nil {
		return nil, err
	}
	fileResidentRepository := file.NewFileResidentRepository(filePaths)
	agentCommandPublisher := agent.NewAgentCommandPublisher(agentCommandCh)
	registerResident := usecase.NewRegisterResident(fileResidentRepository, llmProvider, agentCommandPublisher)
	sendMessageFromBuildingManagerToResident := usecase.NewSendMessageFromBuildingManagerToResident(agentCommandPublisher)
	tuiTUI := tui.NewTUI(registerResident, sendMessageFromBuildingManagerToResident)
	app := &App{
		AgentRuntime: runtime,
		UI:           tuiTUI,
	}
	return app, nil
}

// wire.go:

type App struct {
	AgentRuntime *agents.Runtime
	UI           *tui.TUI
}
