// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kakkky/hakoniwa/agents"
	"github.com/kakkky/hakoniwa/config"
	"github.com/kakkky/hakoniwa/infrastructure/llm"
)

// Injectors from wire.go:

func initializeApp(cfg *config.Config) (*App, error) {
	llmProvider := llm.NewLLMGeminiProvider()
	runtime := agents.NewRuntime(llmProvider)
	app := &App{
		Runtime: runtime,
	}
	return app, nil
}
