// Code generated by MockGen. DO NOT EDIT.
// Source: agent_command_publisher.go
//
// Generated by this command:
//
//	mockgen -source=agent_command_publisher.go -destination=../testing/mock/mock_agent_command_publisher.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kakkky/hakoniwa/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentCommandPublisher is a mock of AgentCommandPublisher interface.
type MockAgentCommandPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCommandPublisherMockRecorder
	isgomock struct{}
}

// MockAgentCommandPublisherMockRecorder is the mock recorder for MockAgentCommandPublisher.
type MockAgentCommandPublisherMockRecorder struct {
	mock *MockAgentCommandPublisher
}

// NewMockAgentCommandPublisher creates a new mock instance.
func NewMockAgentCommandPublisher(ctrl *gomock.Controller) *MockAgentCommandPublisher {
	mock := &MockAgentCommandPublisher{ctrl: ctrl}
	mock.recorder = &MockAgentCommandPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCommandPublisher) EXPECT() *MockAgentCommandPublisherMockRecorder {
	return m.recorder
}

// PublishCommand mocks base method.
func (m *MockAgentCommandPublisher) PublishCommand(ctx context.Context, cmd domain.AgentCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCommand", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishCommand indicates an expected call of PublishCommand.
func (mr *MockAgentCommandPublisherMockRecorder) PublishCommand(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCommand", reflect.TypeOf((*MockAgentCommandPublisher)(nil).PublishCommand), ctx, cmd)
}

// MockAgentCommand is a mock of AgentCommand interface.
type MockAgentCommand struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCommandMockRecorder
	isgomock struct{}
}

// MockAgentCommandMockRecorder is the mock recorder for MockAgentCommand.
type MockAgentCommandMockRecorder struct {
	mock *MockAgentCommand
}

// NewMockAgentCommand creates a new mock instance.
func NewMockAgentCommand(ctrl *gomock.Controller) *MockAgentCommand {
	mock := &MockAgentCommand{ctrl: ctrl}
	mock.recorder = &MockAgentCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCommand) EXPECT() *MockAgentCommandMockRecorder {
	return m.recorder
}

// CommandKey mocks base method.
func (m *MockAgentCommand) CommandKey() domain.AgentCommandKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommandKey")
	ret0, _ := ret[0].(domain.AgentCommandKey)
	return ret0
}

// CommandKey indicates an expected call of CommandKey.
func (mr *MockAgentCommandMockRecorder) CommandKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommandKey", reflect.TypeOf((*MockAgentCommand)(nil).CommandKey))
}

// _isAgentCommand mocks base method.
func (m *MockAgentCommand) _isAgentCommand() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "_isAgentCommand")
}

// _isAgentCommand indicates an expected call of _isAgentCommand.
func (mr *MockAgentCommandMockRecorder) _isAgentCommand() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "_isAgentCommand", reflect.TypeOf((*MockAgentCommand)(nil)._isAgentCommand))
}
